In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [5]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

scaling


In [8]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)


In [9]:
x_train

array([[ 0.17701707, -0.85707195,  0.07048884, ..., -0.83483631,
        -0.61259319, -1.46225864],
       [-0.25668064, -0.85239698, -0.21954897, ..., -0.6091726 ,
         0.44240143, -0.10016004],
       [-1.50646707, -1.14692042, -1.50353199, ..., -1.72720578,
        -0.51257841, -0.28356158],
       ...,
       [-0.18298038, -0.81733466, -0.18416847, ...,  0.89479157,
         0.99570901,  0.98218278],
       [ 0.12882844, -0.97628382,  0.12355959, ...,  0.7274627 ,
        -0.35287739, -0.37389368],
       [-1.20287867, -0.05531369, -1.19456972, ..., -1.02273589,
         0.46175913, -0.19541935]])

In [11]:
y_train

311    B
20     B
175    B
553    B
360    B
      ..
182    M
328    M
81     B
148    B
424    B
Name: diagnosis, Length: 455, dtype: object

In [12]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

numpy arrays to pytorch tensors

In [14]:
x_train_tensors=torch.from_numpy(x_train)
x_test_tensors=torch.from_numpy(x_test)
y_train_tensors=torch.from_numpy(y_train)
y_test_tensors=torch.from_numpy(y_test)

In [16]:
x_train_tensors.shape

torch.Size([455, 30])

defining the model


In [27]:
class MysimpleNN():
  def __init__(self,X):
    self.weights=torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)

    #calculate loss
    loss=-(y*torch.log(y_pred) + (1-y)*torch.log(1-y_pred)).mean()
    return loss


important parameters

In [18]:
learning_rate=0.1
epochs=25

Training pipeline

In [34]:
#create model
model = MysimpleNN(x_train_tensors)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(x_train_tensors)

  #loss calculate
  loss=model.loss_function(y_pred,y_train_tensors)


  #backward pass
  loss.backward()

  # parameter update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"Epoch:{epoch+1} Loss:{loss.item()}")

Epoch:1 Loss:3.24957290890776
Epoch:2 Loss:3.105127917660969
Epoch:3 Loss:2.9578111872783066
Epoch:4 Loss:2.8014918192380733
Epoch:5 Loss:2.647036266157476
Epoch:6 Loss:2.4877911351763937
Epoch:7 Loss:2.3231872450057693
Epoch:8 Loss:2.1589367121697545
Epoch:9 Loss:1.9997900596707954
Epoch:10 Loss:1.84219679183396
Epoch:11 Loss:1.690404571183568
Epoch:12 Loss:1.5447801707460926
Epoch:13 Loss:1.4115350956332309
Epoch:14 Loss:1.292424212411139
Epoch:15 Loss:1.1889278362131235
Epoch:16 Loss:1.1018006597218266
Epoch:17 Loss:1.0305925932584106
Epoch:18 Loss:0.9736198611730853
Epoch:19 Loss:0.9285259035628572
Epoch:20 Loss:0.8929238638325548
Epoch:21 Loss:0.8647288911406749
Epoch:22 Loss:0.8422211858240916
Epoch:23 Loss:0.8240157828865858
Epoch:24 Loss:0.8090315589581134
Epoch:25 Loss:0.7964589182816009


In [35]:
model.bias

tensor([-0.1989], dtype=torch.float64, requires_grad=True)

#Evaluation

In [38]:
#model evaluation

with torch.no_grad():
  y_pred=model.forward(x_test_tensors)
print(y_pred)

tensor([[0.3888],
        [0.5145],
        [0.0906],
        [0.1411],
        [0.7411],
        [0.5039],
        [0.2904],
        [0.5230],
        [0.5296],
        [0.7834],
        [0.7145],
        [0.2467],
        [0.3800],
        [0.3079],
        [0.2276],
        [0.6782],
        [0.3875],
        [0.3009],
        [0.4010],
        [0.2548],
        [0.1779],
        [0.3898],
        [0.3943],
        [0.5757],
        [0.6822],
        [0.5749],
        [0.7868],
        [0.2094],
        [0.1805],
        [0.5449],
        [0.1703],
        [0.1306],
        [0.3339],
        [0.2900],
        [0.6723],
        [0.2028],
        [0.3744],
        [0.2289],
        [0.2166],
        [0.5238],
        [0.1930],
        [0.1739],
        [0.3917],
        [0.2131],
        [0.2696],
        [0.3713],
        [0.1581],
        [0.5884],
        [0.6091],
        [0.6632],
        [0.5098],
        [0.2707],
        [0.4383],
        [0.6536],
        [0.3795],
        [0

In [48]:
y_pred=(y_pred>0.9).float()
accuracy=(y_pred == y_test_tensors).float().mean()
print(f'Accuracy: {accuracy}')

Accuracy: 0.6120344996452332
