In [ ]:
#create model class

import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):

    out=self.network(features)

    return out

In [ ]:
#create dataset
features=torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4848],
        [0.4906],
        [0.5085],
        [0.4784],
        [0.4929],
        [0.5144],
        [0.5107],
        [0.4996],
        [0.5144],
        [0.5065]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights
model.network[0].weight

Parameter containing:
tensor([[-0.2431, -0.2343,  0.4007, -0.2119, -0.3574],
        [-0.0252,  0.1437,  0.2632, -0.4467, -0.1150],
        [ 0.2509, -0.4092,  0.0538, -0.1810, -0.0517]], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[-0.2214, -0.2390, -0.2165]], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00